#' Insert labels in raw SINASC data
#'
#' The function download.sinasc create a data frame about the SINASC data with no treatment. This function is usual to realize the
#' treatment of the data and replace the codes by respective labels.
#'
#' @param x Raw SINASC data generated by the function download.sinasc with all columns.
#'
#' @return A data frame from SINASC with all codes replaced by their respective labels.
#' @export
#'
#' @examples
label.sinasc <- function(x){
  require(foreign)
  require(dplyr)
  require(lubridate)

  base <- x %>%
    select(CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,CODMUNRES,GESTACAO,GRAVIDEZ,
           PARTO,CONSULTAS,DTNASC,HORANASC,SEXO,APGAR1,APGAR5,RACACOR,PESO,IDANOMAL,DTCADASTRO,CODANOMAL,CODMUNNATU,SERIESCMAE,
           DTNASCMAE,RACACORMAE,QTDGESTANT,QTDPARTNOR,QTDPARTCES,IDADEPAI,SEMAGESTAC,TPMETESTIM,CONSPRENAT,MESPRENAT,ESCMAE2010)

  base <- base %>%
    mutate(ESTCIVMAE=recode(ESTCIVMAE,`1`="Solteira",`2`="Casada",`3`="Viúva",`4`="Divorciada",`5`="União Estável",`9`="Ignorado"),

           ESCMAE=recode(ESCMAE,`1`="Nenhuma",`2`="1 a 2 anos",`3`="4 a 7 anos",`4`="8 a 11 anos",`5`="12 e mais",`9`="Ignorado"),

           ESCMAE2010=recode(ESCMAE2010,`0`="Sem escolaridade",`1`="Fundamental I (1ª a 4ª série)",
                             `2`="Fundamental II (5ª a 8º série)",`3`="Médio (antigo 2ª Grau)",
                             `4`="Superior incompleto",`5`="Superior completo",`9`="Ignorado"),

           RACACOR=recode(RACACOR,`1`="Branca",`2`="Preta",`3`="Amarela",`4`="Parda",`5`="Indígena",`9`="Ignorado"),

           IDANOMAL=recode(IDANOMAL,`1`="Sim",`2`="Não",`9`="Ignorado"),

           SEXO=recode(SEXO,`1`="Masculino",`2`="Feminino","M"="Masculino","F"="Feminino",`0`="Ignorado","I"="Ignorado",`9`="Ignorado"),

           GESTACAO=recode(GESTACAO,`1`="Menos de 22 semanas",`2`="22 a 27 semanas",`3`="28 a 31 semanas",`4`="32 a 36 semanas",
                           `5`="37 a 41 semanas",`6`="42 semanas e mais",`9`="Ignorado"),

           GRAVIDEZ=recode(GRAVIDEZ,`1`="Única",`2`="Dupla",`3`="Tripla ou mais",`9`="Ignorado"),

           PARTO=recode(PARTO,`1`="Vaginal",`2`="Cesário"),

           RACACORMAE=recode(RACACORMAE,`1`="Branca",`2`="Preta",`3`="Amarela",`4`="Parda",`5`="Indígena",`9`="Ignorado"),

           DTNASC=dmy(DTNASC),

           DTNASCMAE=dmy(DTNASCMAE),

           DTCADASTRO=dmy(DTCADASTRO),

           HORANASC=paste0(substr(HORANASC,1,2),":", substr(HORANASC,3,4)))

  base <- base %>%
    left_join(CID10%>% select(CID10, DESCR),by=join_by(CODANOMAL==CID10),keep = FALSE)

  base <- base %>%
    left_join(
      left_join(CADMUN%>% select(MUNCOD,MUNNOMEX,UFCOD),TABUF%>% select(SIGLA_UF,CODIGO),by=join_by(UFCOD==CODIGO),keep = F),
      by=join_by(CODMUNRES==MUNCOD),keep = F
    )

  base$CODOCUPMAE <- gsub("^0+","",base$CODOCUPMAE)

  base$CODOCUPMAE <- as.integer(base$CODOCUPMAE)

  base <- base %>%
    left_join(ocup,by=join_by(CODOCUPMAE==CODIGO),keep = F)


  base$TITULO <- ifelse(base$CODOCUPMAE=="999991","Estudante",
                        ifelse(base$CODOCUPMAE=="999992","Dona de Casa",
                               ifelse(base$CODOCUPMAE=="999993","Aposentada/Pensionista",
                                      ifelse(base$CODOCUPMAE=="999994","Desempregada",
                                             ifelse(base$CODOCUPMAE=="516115","Esteticista",
                                                    ifelse(base$CODOCUPMAE=="516135","Massagista",
                                                           ifelse(base$CODOCUPMAE=="514210","Faxineiro",
                                                                  ifelse(base$CODOCUPMAE=="422215","Recepcionista de seguro saúde",
                                                                         ifelse(base$CODOCUPMAE=="354110","Agenciador de propaganda",
                                                                                ifelse(base$CODOCUPMAE=="517315","Agente de segurança penitenciária",
                                                                                       ifelse(base$CODOCUPMAE=="510125","Chefe de cozinha",base$TITULO)))))))))))
  base <- base %>%
    rename(OCUPMAE = TITULO, UF = SIGLA_UF, MUNICIPIO = MUNNOMEX, ANOMALIA = DESCR)

  return(base)
}
